# Setup
title:            F4INX corner
tagline:          'Radiofrequency electronics, EM simulations, ...'
description:      'The corner of Hadrien F4INX: radiofrequency electronics, EM simulations, ....'
baseurl:          '/'
paginate:         5

# About and contact
author:
  name:           'Hadrien Theveneau'
  url:            https://f4inx.github.io

# Collections:
collections:
  - regtests

# Gems
plugins:
  # Jekyll dependencies
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
