name: Link Check

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  linkchecker:
    name: Check links with LinkChecker
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build site
        run: hugo --minify --baseURL "https://f4inx.github.io/"

      - name: Install LinkChecker
        uses: awalsh128/cache-apt-pkgs-action@553a35bb8ebd9fcabcb1c9451aa4c98e1b4ca8a9
        with:
          packages: linkchecker
          version: default

      - name: Run LinkChecker
        run: |
          # Replace PLACEHOLDER with the CI workspace path
          sed -i "s|file:///PLACEHOLDER/|file://$GITHUB_WORKSPACE/public/|" .linkcheckerrc
          linkchecker --config .linkcheckerrc \
            --check-extern --no-warnings \
            ./public/
