name: Link Check

on:
  push:
    branches: [ master, fixes, fixpack ]
  pull_request:
  workflow_dispatch:

jobs:
  lychee:
    name: Check links with lychee
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build site
        run: hugo --minify --baseURL "https://f4inx.github.io/"

      - name: Run lychee
        uses: lycheeverse/lychee-action@v1
        with:
          args: --base https://f4inx.github.io/ --no-progress --verbose ./public/**/*.html
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
